### ISSUE TITLE
Add continuous deployment.

### ISSUE THREAD

**Issue by femiagbabiaka** [dsausa/dsabnb#9]
The current proposed options are Jenkins and CircleCI. CircleCI is free however.

**Comment by femiagbabiaka** [comment]
CircleCI is the consensus for now -- we will move to self hosted jenkins in the future. In order to get the free CircleCI plan, I _think_ (but am not sure) that we need to reach out to CircleCI support. https://circleci.com/pricing/#faq-section-linux

**Comment by zmaril** [comment]
CircleCi is set up. The tests do not pass however so it never could deploy.

**Comment by troygnichols** [comment]
Hi, PR #12 fixes the tests I think
